application/patient/views.py
from application.url_generator import InvoicePath
from application.name_generator import InvoiceName
from flask_login import current_user, login_required
from flask import url_for, render_template, Blueprint, request, session, redirect, jsonify
from application.db_workbench import removeWork, newWork, lastFive
from application.db_users import checkUser, getPractice
from application.db_patient import insertPatient, checkDuplicate, patientSearch, removePatient
from application.forms import mva_patient_form, other_patient_form, getTreatmentForm
from application.db_invoice import updateInvoice, insertInvoice, get_index, queryInvoices, getSingleInvoice, getItems, getInvoiceFileId
from application.models import Patient, AlchemyEncoder
from application import db
import simplejson as json
import re
import subprocess
import os

patient_bp = Blueprint('patient_bp',__name__,
        template_folder='templates', static_folder='static')


@patient_bp.route('')
@login_required
def invoiceTab():
    return render_template('patient/tab_bar.html',
            request_args = json.dumps(request.args,
                sort_keys=True,
                default=str))

@patient_bp.route('/id/<patient_id>')
@login_required
def retrievePatientInfo(patient_id):
    try:
        user = current_user.practice_uuid
        _Patient = db.session.query(Patient).\
                filter(Patient.patient_id == patient_id,
                        Patient.practice_uuid == user).\
                scalar()
        return render_template('patient/tab_bar.html',
                request_args = json.dumps(_Patient, cls=AlchemyEncoder))
    except Exception as ex:
        template = "An exception of type {0} occurred. Arguments:\n{1!r}"
        errorMessage = template.format(type(ex).__name__, ex.args)
        return jsonify(errorMessage), 500


@patient_bp.route('/<patient_id>', methods=('GET','POST'))
@login_required
def invoiceOption(patient_id):
    form_mva = mva_patient_form(current_user.namaf_profession)
    form_other = other_patient_form(current_user.namaf_profession)
    return render_template('patient/patient.html',
            patient_id = patient_id,
            layout_code = current_user.invoice_layout,
            form_mva = form_mva,
            form_other = form_other)


@patient_bp.route('/patient/search', methods=('GET','POST'))
def searchPatient():
    search_term = request.args.get('search_term')
    if search_term is None:
        search_term = request.args.get("term")
    patients = patientSearch(current_user.practice_uuid, search_term)
    return json.dumps(patients, sort_keys=True, default=str)
    #return jsonify(patients)


@patient_bp.route('/patient/delete', methods = ['POST'])
def deletePatient():
    patient_id = request.form.get('patient_id')
    status = removePatient(current_user.practice_uuid, patient_id)
    removeWork(current_user.practice_uuid, 'patient_tab', 'any')
    if status:
        return json.dumps('success')
    return json.dumps('Unable to delelet patient. Please contact system administrator')


@patient_bp.route('/add-work', methods=('GET','POST'))
def addWork():
    work_quality = request.args.get('work_quality')
    work_type = request.args.get('work_type')
    newWork(current_user.uuid, current_user.practice_uuid,  work_type, work_quality)
    return 'success'

@patient_bp.route('/invoice/create', methods=('GET', 'POST'))
@login_required
def createPatient():
    form_mva = mva_patient_form(current_user.namaf_profession)
    form_other = other_patient_form(current_user.namaf_profession)
    return render_template('patient/create.html',
            form_mva = form_mva,
            form_other = form_other,
            layout_code = current_user.invoice_layout,
            page_title = 'Create new patient')


@patient_bp.route('/invoice/continue', methods=('GET', 'POST'))
@login_required
def Continue():
    return render_template('patient/continue.html',
            page_title = 'Continue previous invoice')


@patient_bp.route('/invoice/new', methods=('GET', 'POST'))
@login_required
def newInvoice():
    if request.method == 'POST':
        row = checkDuplicate(current_user.practice_uuid, request.form)
        if row:
            if not request.form.get('continue_patient'):
                return 'Patient already exists.'
        else:
            insertPatient(current_user.practice_uuid, request.form)
            if request.form.get('save_patient'):
                return 'Patient saved'
        patient_name = request.form['patient_name']
        medical_aid = request.form['medical_aid']
        tariff = request.form['tariff']
        item_modifiers = []
        ############## need better solution. Because draft takes new url but does not
        ############## insert invoice. That means if two muplitple people work with the 
        ############### same practice it could lead to duplications of invoice urls
        invoice_index = get_index(current_user.practice_uuid, medical_aid)
        invoice_file_url = InvoicePath(
                medical_aid,
                patient_name,
                invoice_index,
                current_user.practice_folder_id)
        invoice_file_url = invoice_file_url.generate()
        invoice_id = InvoiceName(medical_aid, invoice_index, item_modifiers)
        invoice_id = invoice_id.generate()
        patient_info = request.form.to_dict()
        patient_info['invoice_id'] = invoice_id
        patient_info['invoice_file_url'] = invoice_file_url
        patient_info['invoice_layout'] = current_user.invoice_layout
        newWork(current_user.uuid, current_user.practice_uuid, 'invoice_draft', json.dumps(patient_info))
        form = getTreatmentForm(tariff)
        status = 'new_draft'
    else:
        tariff = request.args.get('tariff')
        status = 'continue_draft'
        form = getTreatmentForm(tariff)
    return render_template('patient/' + tariff[:-5] + '.html',
                status = status,
                form = form)

@patient_bp.route('/invoice/<medical_aid>/<year>/<index>')
@login_required
def Invoice(medical_aid, year, index):
    invoice_id = medical_aid + "/" + year + "/" + index
    invoice = getSingleInvoice(current_user.practice_uuid, invoice_id)
    treatments = getItems(current_user.practice_uuid, invoice_id)
    newWork(current_user.uuid, current_user.practice_uuid, 'invoice_tab', invoice_id)
    invoice['treatments'] = treatments
    form = getTreatmentForm(invoice['tariff'])
    return render_template('patient/' + invoice['tariff'][:-5] + '.html',
            invoice = json.dumps(invoice, sort_keys=True, default=str),
            status = invoice['status'],
            form = form)


@patient_bp.route('/last-five')
def lastFiveTabs():
    work_quality = request.args.get('work_type')
    last_five = lastFive(current_user.uuid, current_user.practice_uuid, work_quality)
    return json.dumps(last_five)


@patient_bp.route('/invoice/generate', methods=['POST'])
def NewInvoice():
    if request.form:
        status = {}
        if request.form['status'] == 'draft':
            removeWork(current_user.uuid, current_user.practice_uuid, 'invoice_draft', 'any')
            try:
                status = insertInvoice(current_user.practice_uuid,
                    current_user.first_name, request.form)
            except Exception as e:
                status['db_status'] = 'Error'
                status['db_description'] = 'Exit code: ' + str(e)
                return json.dumps(status)
        else:
            try:
                status = updateInvoice(current_user.practice_uuid,
                    current_user.first_name, request.form)
            except Exception as e:
                status['db_status'] = 'Error'
                status['db_description'] = 'Exit code: ' + str(e)
                return json.dumps(status)
        method = None
        if status['db_status'] != 'Success':
            return json.dumps(status)
        if request.form.get('save_as_odt') or request.form.get('save_as_pdf'):
            try:
                practice = getPractice(practice_uuid = current_user.practice_uuid)
                practice['uuid_bin'] = ''
                practice['created_on'] = ''
                res_dict = {
                    "practice" : practice,
                    "invoice": request.form,
                    "treatments": request.form.getlist('treatments'),
                    "descriptions": request.form.getlist('description'),
                    "units": request.form.getlist('units'),
                    "post_values": request.form.getlist('post_value'),
                    "dates": request.form.getlist('date'),
                    "modifiers": request.form.getlist('modifier'),
                    "save_as_pdf": request.form.get("save_as_pdf"),
                    "save_as_odt": request.form.get("save_as_odt")
                    }
                to_json = json.dumps(res_dict)
            except Exception as e:
                status['swriter_status'] = 'Failed'
                status['swriter_description'] = 'Wrap form into JSON failed.' + str(e)
                return status
            try:
                _sReturnValInvFile = subprocess.check_output([os.getenv("LIBPYTHON"),
                    os.getenv("APP_URL") + '/swriter/main.py', to_json])
                status['swriter_status'] = 'Success'
                status['swriter_description'] = _sReturnValInvFile.decode('ascii')
                _sReturnValSyncFile = subprocess.check_output([os.getenv('SYSTEM_BASH'),
                    os.getenv("APP_URL") + "/bin/sync_practice.sh",
                    os.getenv("PHP"),
                    os.getenv("OC_DIR"),
                    str(current_user.practice_folder_id)])
            except subprocess.CalledProcessError as e:
                status['swriter_status'] = 'Error'
                status['swriter_description'] = 'Exit code: ' + str(e.returncode)
                return json.dumps(status)

application/templates/navigation.html
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default">
    <a class="navbar-brand" href="/">Pasclepius</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item home">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if current_user.is_authenticated %}

            {% if current_user.practice_uuid %}
              <li class="nav-item patient">
                <a class="nav-link" href="/patient">Patient</a>
              </li>
              <li class="nav-item account">
                <a class="nav-link" href="/account">Account</a>
              </li>
              <li class="nav-item profile">
                <a class="nav-link" href="/profile">Settings</a>
              </li>     
              <li class="nav-item nextcloud">
                <a class="nav-link" href='{{ NEXTCLOUD_DOMAIN_FULL }}' target="_blank">Nextcloud</a>
              </li>       
            {% else %}
              <li class="nav-item setup">
                <a class="nav-link" href="/setup">Setup</a>
              </li>
            {% endif %}
            <li class="nav-item logout">
              <a class="nav-link" href="/auth/logout">Logout</a>
            </li>
        {% else %}
        <li class="nav-item login">
          <a class="nav-link" href="/auth/login">Login</a>
        </li>
        {% endif %}
      </ul>
      {% if current_user.is_authenticated and current_user.practice_uuid%}
      <span class="navbar-text" style="padding-right: 2em; max-width: 15em; white-space: nowrap; text-overflow: ellipsis; overflow: hidden;">
        Practice: <p id="practice_name_navbar" style="padding:0;margin:0;display:inline">{{  current_user.practice_name }}</p>
      </span>

      <form class="search form-inline my-2 my-lg-0" autocomplete="off">
        <input id="patient_name" class="form-control mr-sm-2" name="patient_name" type="search" placeholder="Search patients">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      {% endif %}
    </div>
  </nav>
  <script>
    $(document).ready(function(){
      if(window.location.href.match('patient')){
        $('.patient').addClass('active');
      }
      else if (window.location.href.match('setup')){
        $('.setup').addClass('active');
      }
      else if (window.location.href.match('account')){
        $('.account').addClass('active');
      }
      else if (window.location.href.match('profile')){
        $('.profile').addClass('active');   
      }
      else if (window.location.href.match('login')){
        $('.login').addClass('active');
      }
      else if(window.location.href.match('home')) {
        $('.home').addClass('active');
      }
      else{
        $('.home').addClass('active');
      }



        function removeActive(x) {
            for (var i = 0; i < x.length; i++) {
                x[i].classList.remove("autocomplete-active");
            }
        }
        
        
        function addActive(x) {
            if (!x) return false;
            removeActive(x);
            if (currentFocus >= x.length) currentFocus = 0;
            if (currentFocus < 0) currentFocus = (x.length - 1);
            x[currentFocus].classList.add("autocomplete-active");
        }


        $(document).on("keyup", ".search", function (e) {
            e.preventDefault();
            var currentFocus;
            var input_element = document.getElementById("patient_name")
            var url = "{{ url_for('patient_bp.searchPatient') }}";
            var a, b, i, val = input_element.value;
            var name = input_element.value
                $.ajax({
                type: "GET",
                url: url,
                data: {search_term: name}, 
                dataType: 'json',
                success: function (returnData) {
                    if(returnData && returnData.length <= 5){
                    // if (returnData.length <= 5){
                      var names = [], range = returnData.length;
                    }
                    else{
                     var names = [], range = 5
                    }
                    for (i = 0; i < range; i++) {
                        names[i] = returnData[i]['patient_name'];
                    }
                    closeAllLists();
                    if (!val) { return false;}
                    currentFocus = -1;
                    var a = document.createElement("DIV");
                    a.setAttribute("id", "autocomplete-list");
                    a.setAttribute("class", "autocomplete-items");
                    input_element.parentNode.appendChild(a);
                    for (i = 0; i < names.length; i++) {
                        if (names[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                            var b = document.createElement("DIV");
                            b.style.display = "flex";
                            b.style.justifyContent = "flex-end";
                            b.style.alignItems = "center";
                            b.innerHTML = "<strong>" + names[i].substr(0, val.length) + "</strong>";
                            b.innerHTML += names[i].substr(val.length);
                            for (const [key, value] of Object.entries(returnData[i])){
                              b.innerHTML += "<input type='hidden' value='" + value + "' name='" + key + "'>";
                            }
                            b.addEventListener("click", function(e) {
                              var patient_details = {};
                              var inputCollection = this.getElementsByTagName("input")
                              for (let i = 0; i < inputCollection.length; i++) {
                                const element = inputCollection[i];
                                patient_details[element.name] = element.value
                              }
                                closeAllLists();
                                var uri = xwwwfurlenc(patient_details);
                                window.location.href = "/patient?" + uri
                            });
                            a.appendChild(b);
                        }
                    }


            function closeAllLists(elmnt) {
                var x = document.getElementsByClassName("autocomplete-items");
                for (var i = 0; i < x.length; i++) {
                    if (elmnt != x[i] && elmnt != input_element) {
                    x[i].parentNode.removeChild(x[i]);
                    }
                }
            }
            document.addEventListener("click", function (e) {
                closeAllLists(e.target);
            });

                },
            });
        });
    })



    function xwwwfurlenc(srcjson){
    if(typeof srcjson !== "object")
      if(typeof console !== "undefined"){
        return null;
      }
    u = encodeURIComponent;
    var urljson = "";
    var keys = Object.keys(srcjson);
    for(var i=0; i <keys.length; i++){
        urljson += u(keys[i]) + "=" + u(srcjson[keys[i]]);
        if(i < (keys.length-1))urljson+="&";
    }
    return urljson;
}

  </script>
</header>

application/templates/reset_banking.html
{% include 'profile.html' %}
{% block content %}
    {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}
            <div class="tab-pane" id="banking">
                <form method="post">
                    {{ form_banking.hidden_tag() }}
                    <div class="form-group">
                        {{ form_banking.bank_holder.label}}
                        {{ form_banking.bank_holder(value=bank_holder, class="form-control w-25 p-3") }}
                    </div>
                    <div class="form-group">
                        {{ form_banking.bank_account.label}}
                        {{ form_banking.bank_account(value=bank_account, class="form-control w-25 p-3") }}
                    </div>
                    <div class="form-group">
                        {{ form_banking.bank_branch.label}}
                        {{ form_banking.bank_branch(value=bank_branch, class="form-control w-25 p-3") }}
                    </div>
                        <div class="form-group">
                        {{ form_banking.bank.label}}
                        {{ form_banking.bank(value=bank, class="form-control w-25 p-3") }}
                    </div>
                    {{ form_banking.submit }}
                </form>
            </div>
        </div>
    </div>
</div>

 {% endblock %}

application/templates/reset_layout.html
{% include 'profile.html' %}
{% block content %}
    {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}
            <div class="tab-pane" id="layout">
                <form method="post">
                    <div class="form-group row">
                        <div class="col-sm-2">Choose Invoice Layout</div>
                        <div class="col-sm-10">
                            {{ form_layout.hidden_tag() }}
                            <div class="form-check">
                                {{ form_layout.phone(class="form-check-input") }}
                                {{ form_layout.phone.label(class_="form-check-label") }}
                                
                            </div>
                            <div class="form-check">
                                {{ form_layout.fax( class="form-check-input") }}
                                {{ form_layout.fax.label(class_="form-check-label") }}
                                
                            </div>
                            <div class="form-check">
                                {{ form_layout.hospital(class="form-check-input") }}
                                {{ form_layout.hospital.label(class_="form-check-label") }}
                                
                            </div>
                            <div class="form-check">
                                {{ form_layout.diagnosis(class="form-check-input") }}
                                {{ form_layout.diagnosis.label(class_="form-check-label") }}
                            
                            </div>
                        </div>
                    </div>
                    {{ form_layout.submit }}
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        if ('{{layout_code}}' == 1){
        }
        else if ('{{layout_code}}' == 2){
            $("#phone").prop("checked", true);
        }
        else if ('{{layout_code}}' == 3){
            $("#phone").prop("checked", true);
            $("#fax").prop("checked", true);
        }
        else if ('{{layout_code}}' == 4){
            $("#hospital").prop("checked", true);
        }
        else if ('{{layout_code}}' == 5){
            $("#phone").prop("checked", true);
            $("#hospital").prop("checked", true);
        }
        else if ('{{layout_code}}' == 6){
            $("#phone").prop("checked", true);
            $("#fax").prop("checked", true);
            $("#hospital").prop("checked", true);
        }
        else if ('{{layout_code}}' == 7){
            $("#diagnosis").prop("checked", true);
            $("#hospital").prop("checked", true);
        }
        else if ('{{layout_code}}' == 8){
            $("#phone").prop("checked", true);
            $("#diagnosis").prop("checked", true);
            $("#hospital").prop("checked", true);
        }
        else if ('{{layout_code}}' == 9){
            $("#phone").prop("checked", true);
            $("#fax").prop("checked", true);
            $("#diagnosis").prop("checked", true);
            $("#hospital").prop("checked", true);
        }
        else if ('{{layout_code}}' == 10){
            $("#diagnosis").prop("checked", true);
        }
        else if ('{{layout_code}}' == 11){
            $("#phone").prop("checked", true);
            $("#diagnosis").prop("checked", true);
        }
        else if ('{{layout_code}}' == 12){
            $("#phone").prop("checked", true);
            $("#fax").prop("checked", true);
            $("#diagnosis").prop("checked", true);
        }
    });
    </script>

 {% endblock %}

application/templates/reset_password.html
{% include 'profile.html' %}
{% block content %}
    {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}
                   <form method="post">
                    {{ form_password.hidden_tag() }}
                    <div class="form-group">
                        {{ form_password.password.label(for="password", class_="required") }}
                        {{ form_password.password(class="form-control w-25 p-3") }}
                        {% for error in form_password.password.errors %}
                          <span style="color: red;">{{ error }}</span>
                        {% endfor %} 
                        </div>
                        <div class="form-group">
                        {{ form_password.confirm.label(for="confirm", class_="required") }}
                        {{ form_password.confirm(class="form-control w-25 p-3") }}
                        </div>
                        {{ form_password.submit }}
                   </form>
        </div>
    </div>
</div>

 {% endblock %}

application/templates/reset_personal.html
{% include 'profile.html' %}
{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}

            <div class="tab-pane" id="personal">
                <form method="post">
                    <div class="form-row">
                        {{ form_personal.hidden_tag() }}
                        <div class="form-group col-md-2">
                            {{ form_personal.title.label }}
                            {{ form_personal.title(value=title, class="form-control") }}
                        </div>
                        <div class="form-group col-md-5">
                            {{ form_personal.first_name.label }}
                            {{ form_personal.first_name(value=first_name, class="form-control") }}
                        </div>
                        <div class="form-group col-md-5">
                            {{ form_personal.second_name.label }}
                            {{ form_personal.second_name(value=second_name, class="form-control") }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            {{ form_personal.phone.label }}
                            {{ form_personal.phone(value=phone,class="form-control") }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form_personal.cell.label }}
                            {{ form_personal.cell(value=cell, class="form-control") }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form_personal.fax.label }}
                            {{ form_personal.fax(value=fax, class="form-control") }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            {{ form_personal.pob.label }}
                            {{ form_personal.pob(value=pob, class="form-control") }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form_personal.city.label }}
                            {{ form_personal.city(value= city, class="form-control") }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form_personal.country.label }}
                            {{ form_personal.country(value=country, class="form-control") }}
                        </div>
                    </div>
                        <div class="form-group">
                            {{ form_personal.qualification.label }}
                            {{ form_personal.qualification(value=qualification, class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ form_personal.specialisation.label }}
                            {{ form_personal.specialisation(value=specialisation, class="form-control") }}
                        </div>
                        {{ form_personal.submit }}
                </form> 
            </div>
        </div>
    </div>
</div>
<script>
    $("#title").val('{{ title }}').attr("selected","selected");
</script>

 {% endblock %}

application/templates/reset_practice.html
{% include 'profile.html' %}
{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}

            <div class="tab-pane" id="personal">
                <form method="post">
                    {{ form_practice.hidden_tag() }}
                    <div class="form-group">
                        {{ form_practice.practice_name.label }}
                        {{ form_practice.practice_name(value=practice_name, class="form-control w-25 p-3") }}
                    <div class="form-group">
                        {{ form_practice.practice_number.label }}
                        {{ form_practice.practice_number(value=practice_number, class="form-control w-25 p-3") }}
                    </div>
                    <div class="form-group">
                        {{ form_practice.hpcna_number.label }}
                        {{ form_practice.hpcna_number(value=hpcna_number, class="form-control w-25 p-3") }}
                    </div>
                    {{ form_practice.submit }}
                </form> 
            </div>
        </div>
    </div>
</div>

 {% endblock %}